# Generated by Django 2.2.14 on 2021-02-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='CrudModel',
        ),
    ]
